-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "dealDescription" TEXT NOT NULL DEFAULT 'No deal',
ADD COLUMN     "endDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "isDeal" BOOLEAN NOT NULL DEFAULT false;
